### ISSUE TITLE
uhdtodrf has error TypeError('slice indices must be integers or None or have an __index__ method')

### ISSUE THREAD

**Issue by ashley-b** [MITHaystack/digital_rf#34]
I get the following error starting a capture
```
Processor caught this error: TypeError('slice indices must be integers or None or have an __index__ method')
<class 'TypeError'> uhdtodrf.py 1377
Traceback (most recent call last):
  File "/home/ashley/OpenSource/sdr/digital_rf/./python/tools/uhdtodrf.py", line 2128, in <module>
    rec1.run(**runopts)
  File "/home/ashley/OpenSource/sdr/digital_rf/./python/tools/uhdtodrf.py", line 1157, in run
    if not proc_threads[0].isAlive():
AttributeError: 'Thread' object has no attribute 'isAlive'
```
I traced it back to this line https://github.com/MITHaystack/digital_rf/blob/021271709b3929e255d42824759442bc6c439385/python/tools/uhdtodrf.py#L1336
Am guessing this should be integer division?

**Comment by ryanvolz** [comment]
Easy enough fix, thanks for the bug report! I'll aim to get this in the next release (soon).
