### ISSUE TITLE
Thor issues with GR 3.9

### ISSUE THREAD

**Issue by ryanvolz** [MITHaystack/digital_rf#35]
Report from Frank.

Running thor.py with multiple channels:
```
|lwa_a|start @ sample 0: 1626815339+0.0 (20335191737500000)
|lwa_b|start @ sample 0: 1626815339+0.0 (20335191737500000)gr::log :error: thread_body_wrapper - ERROR thread[thread-per-block[2]: <block digital_rf_channel_sink(2)>]: AttributeError: 'list_iterator' object has no attribute 'start'
[WARNING] [0/Radio#0] Attempting to set tick rate to 0. Skipping.
```

When setting a stop time:
```
lwa_a|rx_time tag @ sample 0: 1626815430+0.0 (20335192875000000)..........................................................done
Traceback (most recent call last):
  File "/home/midasop/radioconda/bin/thor.py", line 1839, in <module>
    args.func(args)
  File "/home/midasop/radioconda/bin/thor.py", line 1833, in _run_thor
    thor.run(**runopts)
  File "/home/midasop/radioconda/bin/thor.py", line 1112, in run
    stop_enum = uhd.stream_cmd.STREAM_MODE_STOP_CONTINUOUS
AttributeError: type object 'gnuradio.uhd.uhd_python.stream_cmd_t' has no attribute 'STREAM_MODE_STOP_CONTINUOUS'
```
Also, `drf mirror mv` didn't copy the `drf_properties.h5` along with the data?
Also also, `drf_sti.py` is not loading the center frequency correctly anymore?

**Comment by ryanvolz** [comment]
`drf mirror mv` *copies* `drf_properties.h5` (confirmed that this still works), which is expected despite the command to *move* because when mirroring we don't want to break any ongoing writing to the source directory.

`drf_sti.py` seems to show the correct center frequency from some thor-recorded data, but it does it in the plot title and doesn't use it to label the y-axis. This is as it has always been, but perhaps we should change that in some future improved version of the plotting tools.
