### ISSUE TITLE
Building srt-py crashes on digital_rf

### ISSUE THREAD

**Issue by AlexKurek** [MITHaystack/digital_rf#54]
Im trying to do:
`conda build srt-py --python 3.10.13 --channel conda-forge`
Im getting:

```
[...]
The following packages are incompatible
    ├─ digital_rf is installable with the potential options
    │  ├─ digital_rf 2.6.3 would require
    │  │  └─ python_abi * *_cp27mu, which can be installed;
    │  ├─ digital_rf [2.6.3|2.6.4|...|2.6.7] would require
    │  │  └─ python_abi 3.6.* *_cp36m, which can be installed;
    │  ├─ digital_rf 2.6.3 would require
    │  │  └─ python_abi * *_cp36m, which can be installed;
    │  ├─ digital_rf [2.6.3|2.6.4|...|2.6.7] would require
    │  │  └─ python_abi 3.7.* *_cp37m, which can be installed;
    │  ├─ digital_rf 2.6.3 would require
    │  │  └─ python_abi * *_cp37m, which can be installed;
    │  ├─ digital_rf [2.6.3|2.6.4|...|2.6.8] would require
    │  │  └─ python_abi 3.8.* *_cp38, which can be installed;
    │  ├─ digital_rf [2.6.5|2.6.6|2.6.7|2.6.8] would require
    │  │  └─ python_abi 3.9.* *_cp39, which can be installed;
    │  ├─ digital_rf [2.6.7|2.6.8] would require
    │  │  └─ python_abi 3.10.* *_cp310, which can be installed;
    │  └─ digital_rf [2.6.7|2.6.8] would require
    │     └─ python_abi 3.11.* *_cp311, which can be installed;
    └─ python_abi 3.12* *_cp312 is not installable because it conflicts with any installable versions previously reported.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 172, in do_call
        result = plugin_subcommand.action(getattr(args, "_args", args))
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda_build/plugin.py", line 10, in build
        execute(*args, **kwargs)
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 578, in execute
        outputs = api.build(
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda_build/api.py", line 255, in build
        return build_tree(
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 3762, in build_tree
        packages_from_this = build(
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 2556, in build
        create_build_envs(top_level_pkg, notest)
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 2392, in create_build_envs
        raise e
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda_build/build.py", line 2363, in create_build_envs
        environ.get_package_records(
      File "/home/kurek/miniconda3/lib/python3.10/site-packages/conda_build/environ.py", line 922, in get_package_records
        raise DependencyNeedsBuildingError(exc, subdir=subdir)
    conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'package digital_rf-2.6.7-py310h0679f23_3 requires python_abi 3.10.* *_cp310, but none of the providers can be installed'}
```

**Comment by AlexKurek** [comment]
It was solved by https://github.com/MITHaystack/srt-py/pull/20 so I guess I should close this?
