### ISSUE TITLE
PyPI release: `numpy` v2 compatible

### ISSUE THREAD

**Issue by lucaspar** [MITHaystack/digital_rf#62]
Hi @ryanvolz, just checking if we can expect a numpy v2 compatible release on PyPI soon.

I'm getting the following import error so far. It seems the conda release might work right now, but a PyPI release would let us use `digital-rf` with several other package managers. 

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/user/drf-demo/digitalrf_demo.py", line 7, in <module>
    import digital_rf as drf
  File "/home/user/drf-demo/.venv/lib/python3.12/site-packages/digital_rf/__init__.py", line 7, in <module>
    from .digital_rf_hdf5 import *  # noqa: F401,F403
  File "/home/user/drf-demo/.venv/lib/python3.12/site-packages/digital_rf/digital_rf_hdf5.py", line 36, in <module>
    from . import _py_rf_write_hdf5, digital_metadata, list_drf
Traceback (most recent call last):
  File "/home/user/drf-demo/.venv/lib/python3.12/site-packages/numpy/core/_multiarray_umath.py", line 44, in __getattr__
    raise ImportError(msg)
ImportError: 
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.
```

**Comment by rrobinett** [comment]
I am having the same problem running digital_rf in Ubuntu 24.04.  
It runs only on numpy 1.26.4, but Ubuntu includes 2.1.2 and all other python packages require numpy 2.1.1*
It is a real programming mess to install and run two different versions of numpy.

**Comment by ryanvolz** [comment]
I hear you! I intend to get binary releases back on PyPI at some point, but it requires re-doing the automated build since the old way that I used for prior releases doesn't work anymore. In the meantime I recommend [the conda package](https://github.com/MITHaystack/digital_rf?tab=readme-ov-file#using-conda-package) which is much easier to keep up to date. And if that doesn't work for you, then you can [build the latest release from source](https://github.com/MITHaystack/digital_rf?tab=readme-ov-file#using-source-code-package) and have compatibility with numpy 2.

**Comment by ryanvolz** [comment]
2.6.10 released with numpy v2 compatibility and wheels on PyPI.
